# Generated by Django 2.2.19 on 2023-03-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230320_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientsinrecipes',
            options={'verbose_name': 'Связь ингредиентов и рецептов', 'verbose_name_plural': 'Связь ингредиентов и рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipestags',
            options={'verbose_name': 'Связь тегов и рецептов', 'verbose_name_plural': 'Связь тегов и рецептов'},
        ),
    ]
